### ISSUE TITLE
redmine 5.1.2安装后启动报错

### ISSUE THREAD

**Issue by whoarei** [mingming-cn/redmine_work_wechat#2]
按照安装说明，git clone到插件目录，然后重启了redmine就报这种错误了：
```shell
app/views/layouts/base.html.erb:121
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
I, [2024-06-13T02:07:41.792486 #1]  INFO -- : Started GET "/" for 192.168.50.4 at 2024-06-13 02:07:41 +0000
I, [2024-06-13T02:07:41.793502 #1]  INFO -- : Processing by WelcomeController#index as HTML
I, [2024-06-13T02:07:41.799434 #1]  INFO -- :   Current user: libb (id=5)
I, [2024-06-13T02:07:41.804565 #1]  INFO -- :   Rendered welcome/index.html.erb within layouts/base (Duration: 2.5ms | Allocations: 660)
local ticket:
I, [2024-06-13T02:07:41.816916 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 14.9ms | Allocations: 6008)
I, [2024-06-13T02:07:41.817232 #1]  INFO -- : Completed 500 Internal Server Error in 24ms (ActiveRecord: 4.9ms | Allocations: 7359)
F, [2024-06-13T02:07:41.818142 #1] FATAL -- :
ActionView::Template::Error (undefined method `split' for nil:NilClass):
    1: <% if RedmineWorkWechat::settings_hash["open_in_default_browser"] %>
    2:   <% js_sdk_config = RedmineWorkWechat::DefaultBrowser::js_sdk_config(request) %>
    3:
    4:   <script>
    5:       ww.register({

plugins/redmine_work_wechat/lib/redmine_work_wechat/work_wechat.rb:15:in `get_http_client'
plugins/redmine_work_wechat/lib/redmine_work_wechat/work_wechat.rb:58:in `get_access_token'
plugins/redmine_work_wechat/lib/redmine_work_wechat/work_wechat.rb:33:in `get_jsapi_ticket'
plugins/redmine_work_wechat/lib/redmine_work_wechat/default_browser.rb:12:in `js_sdk_config'
plugins/redmine_work_wechat/app/views/default_browser/_default_browser_foot.html.erb:2
lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:59:in `map'
lib/redmine/hook/view_listener.rb:59:in `block in render_on'
lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:66:in `each'
lib/redmine/hook.rb:66:in `block in call_hook'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:101:in `call_hook'
app/views/layouts/base.html.erb:121
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
I, [2024-06-13T02:08:31.659942 #1]  INFO -- : Started GET "/" for 192.168.50.4 at 2024-06-13 02:08:31 +0000
I, [2024-06-13T02:08:31.661149 #1]  INFO -- : Processing by WelcomeController#index as HTML
I, [2024-06-13T02:08:31.673640 #1]  INFO -- :   Current user: libb (id=5)
I, [2024-06-13T02:08:31.679193 #1]  INFO -- :   Rendered welcome/index.html.erb within layouts/base (Duration: 2.6ms | Allocations: 660)
local ticket:
I, [2024-06-13T02:08:31.693162 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 16.6ms | Allocations: 6010)
I, [2024-06-13T02:08:31.693505 #1]  INFO -- : Completed 500 Internal Server Error in 32ms (ActiveRecord: 10.3ms | Allocations: 7487)
F, [2024-06-13T02:08:31.694544 #1] FATAL -- :
ActionView::Template::Error (undefined method `split' for nil:NilClass):
    1: <% if RedmineWorkWechat::settings_hash["open_in_default_browser"] %>
    2:   <% js_sdk_config = RedmineWorkWechat::DefaultBrowser::js_sdk_config(request) %>
    3:
    4:   <script>
    5:       ww.register({

plugins/redmine_work_wechat/lib/redmine_work_wechat/work_wechat.rb:15:in `get_http_client'
plugins/redmine_work_wechat/lib/redmine_work_wechat/work_wechat.rb:58:in `get_access_token'
plugins/redmine_work_wechat/lib/redmine_work_wechat/work_wechat.rb:33:in `get_jsapi_ticket'
plugins/redmine_work_wechat/lib/redmine_work_wechat/default_browser.rb:12:in `js_sdk_config'
plugins/redmine_work_wechat/app/views/default_browser/_default_browser_foot.html.erb:2
lib/redmine/hook/view_listener.rb:61:in `block (2 levels) in render_on'
lib/redmine/hook/view_listener.rb:59:in `map'
lib/redmine/hook/view_listener.rb:59:in `block in render_on'
lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:66:in `each'
lib/redmine/hook.rb:66:in `block in call_hook'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:101:in `call_hook'
app/views/layouts/base.html.erb:121
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by mingming-cn** [comment]
有点BUG，我修复一下，稍后发布个新版本。

**Comment by mingming-cn** [comment]
可以拉取 master 分支再试一下，应该可以了。

**Comment by huisunan** [comment]
> 可以拉取 master 分支再试一下，应该可以了。

还是不行

**Comment by mingming-cn** [comment]
> > 可以拉取 master 分支再试一下，应该可以了。
> 
> 还是不行

应该是因为插件默认启用，但是没有相关配置导致的，我这边在开发中已经有了相关配置，所以没遇到问题。

我看一下如何解决。

**Comment by huisunan** [comment]
NoMethodError (undefined method `gsub' for nil:NilClass):
还是有些问题，麻烦帮忙定位一下  

plugins/redmine_work_wechat/lib/redmine_work_wechat/helper.rb:53:in `block in arr_to_quote'
plugins/redmine_work_wechat/lib/redmine_work_wechat/helper.rb:53:in `map'
plugins/redmine_work_wechat/lib/redmine_work_wechat/helper.rb:53:in `arr_to_quote'
plugins/redmine_work_wechat/lib/redmine_work_wechat/helper.rb:49:in `render_markdown'
plugins/redmine_work_wechat/lib/redmine_work_wechat/patches/models/journal_patch.rb:38:in `send_notification'
app/controllers/issues_controller.rb:652:in `save_issue_with_child_records'
app/controllers/issues_controller.rb:207:in `update'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by huisunan** [comment]
请问一下这个Redmine和企业微信用户是如何对应的

**Comment by mingming-cn** [comment]
> 请问一下这个Redmine和企业微信用户是如何对应的

目前是通过 邮箱 作为 企业微信的 成员ID 发送通知的，需要企业微信的成员ID与Redmine用户邮箱相同。

**Comment by mingming-cn** [comment]
以上问题应该都已修复，可以拉取 master 代码试一下。
@whoarei  @huisunan

**Comment by learuhu** [comment]
> > 请问一下这个Redmine和企业微信用户是如何对应的
> 
> 目前是通过 邮箱 作为 企业微信的 成员ID 发送通知的，需要企业微信的成员ID与Redmine用户邮箱相同。

企微user_id肯定不可能和邮箱相同，这个可是个大问题

**Comment by mingming-cn** [comment]
> > > 请问一下这个Redmine和企业微信用户是如何对应的
> > 
> > 
> > 目前是通过 邮箱 作为 企业微信的 成员ID 发送通知的，需要企业微信的成员ID与Redmine用户邮箱相同。
> 
> 企微user_id肯定不可能和邮箱相同，这个可是个大问题

因为我们公司 企微user_id 和 邮箱相同，所以现在是这个逻辑，后续会加上自定义的选项。

**Comment by mingming-cn** [comment]
> > > 请问一下这个Redmine和企业微信用户是如何对应的
> > 
> > 
> > 目前是通过 邮箱 作为 企业微信的 成员ID 发送通知的，需要企业微信的成员ID与Redmine用户邮箱相同。
> 
> 企微user_id肯定不可能和邮箱相同，这个可是个大问题

最新的代码已经支持自定义了。

**Comment by mingming-cn** [comment]
如果没有其它问题，我将在稍后关闭此 issue。
